### ISSUE TITLE
Please add a "latest" tag to hub.docker.com images

### ISSUE THREAD

**Issue by ThisIsTheOnlyUsernameAvailable** [giantswarm/coredns-warnlist-plugin#116]
Fantastic plugin -- thank you!

To simplify upgrades, it would help greatly if you could tag your hub.docker.com images with 'latest' or similar.  This will ensure those with automation (eg ouroboros, watchtower, etc) can keep up with development.

**Comment by stone-z** [comment]
Hey @ThisIsTheOnlyUsernameAvailable, thanks for your interest! I'm glad you are enjoying the project. 

We tend to discourage `latest` tags :slightly_frowning_face: they just introduce so many fun new ways for things to change unexpectedly and that wakes us up at night. This plugin does not change very often anyway, but surprise changes to DNS... :grimacing: 

I'm not a user of ouroboros or watchtower, but most automation we rely on currently can track new tags and update "downstream" projects that way. Dependabot or Renovate, for example, can update references to this image on GitHub or other version control systems, and [Flux can track image releases](https://fluxcd.io/docs/guides/image-update/ )in a Kubernetes context. Maybe one of those will work for your use case? If not, I'd be open to hearing about it and maybe we can figure something out.

**Comment by ThisIsTheOnlyUsernameAvailable** [comment]
Thanks very much for the advice, @stone-z.  I'll update my workflow accordingly.
